### ISSUE TITLE
Issue with CNV GWAS 

### ISSUE THREAD

**Issue by SaraNara** [waldronlab/CNVRanger#24] opened 2021-03-16 02:58 UTC
Hello;
I am trying to do association analysis for with CNV using CNV ranger. I am getting the following issue;

> segs.pvalue.gr <- cnvGWAS(phen.info, chr.code.name=chr.code.name, method.m.test="none")
sh: /Users/sara/Library/Application Support/CNVRanger/example/PLINK/plink-1.07-mac-intel/plink: Bad CPU type in executable
Error in file(file, "rt") : cannot open the connection
In addition: Warning messages:
1: In file.rename(from, to) :
  cannot rename file '/Users/sara/Library/Application Support/CNVRanger/example/PLINK/plink-1.07-mac-intel/plink.gvar.summary' to '/Users/sara/Library/Application Support/CNVRanger/example/PLINK/plink-1.07-mac-intel/plink.gvar.summary.BT', reason 'No such file or directory'
2: In file(file, "rt") :
  cannot open file '/Users/sara/Library/Application Support/CNVRanger/example/PLINK/plink-1.07-mac-intel/plink.gvar.summary.BT': No such file or directory
> segs.pvalue.gr
Error: object 'segs.pvalue.gr' not found

I see that it can not access the PLINK 1.07. Can you help me to solve this issue? I am using the example data given with CNV Ranger.

**Comment by lgeistlinger** [comment] 2021-03-16 12:42
@viniciushdasilva might be able to help with that?

**Comment by viniciushdasilva** [comment] 2021-03-16 14:20
@SaraNara, you are using macOS, right?
Seems that some versions of mac have this 'Bad CPU type in executable' problem. All the subsequent errors should be resolved without this error. 

I have found this discussion [](https://discussions.apple.com/thread/250777998), which presented the following solution to get rid of this error: [](https://support.apple.com/en-us/HT208050)

If the error persists, please let us know!

**Comment by SaraNara** [comment] 2021-03-16 16:32
Thank you for your response. yes I used macOS. Already my terminal had zsh as default. However, I tried to change it again as mention in the link provided. Still, I have the same problem. Any alternative solution?????

Also, I tried to install The CNV ranger in windows. However, I had some issues with installation. I had to install all dependencies one by one. I used R version 4.1. How do I solve this problem too?

**Comment by lgeistlinger** [comment] 2021-04-18 18:13
Hi @viniciushdasilva I can reproduce this problem on my mac.

It actually starts one step earlier when you try to execute the example section in the man page of `cnvGWAS` 

> ?cnvGWAS
> data.dir <- system.file("extdata", package="CNVRanger")
>      
>      phen.loc <- file.path(data.dir, "Pheno.txt")
>      cnv.out.loc <- file.path(data.dir, "CNVOut.txt")
>      map.loc <- file.path(data.dir, "MapPenn.txt")
>      
>      phen.info <- setupCnvGWAS('Example', phen.loc, cnv.out.loc, map.loc)
trying URL 'http://zzz.bwh.harvard.edu/plink/dist/plink-1.07-mac-intel.zip'
Content type 'application/zip' length 3012160 bytes (2.9 MB)
==================================================
downloaded 2.9 MB

Error in system2(plink.path, args = "--noweb", stdout = TRUE, stderr = FALSE) : 
  error in running command

If you follow the example further: 

> df <- '16 1A
+      25 4A
+      29 25LG1
+      30 25LG2
+      31 LGE22'
>      
>      chr.code.name <- read.table(text=df, header=FALSE)
>      segs.pvalue.gr <- cnvGWAS(phen.info, chr.code.name=chr.code.name)
sh: /Users/ludwig/Library/Application Support/CNVRanger/Example/PLINK/plink-1.07-mac-intel/plink: Bad CPU type in executable
Error in file(file, "rt") : cannot open the connection
In addition: Warning messages:
1: In file.rename(from, to) :
  cannot rename file '/Users/ludwig/Library/Application Support/CNVRanger/Example/PLINK/plink-1.07-mac-intel/plink.gvar.summary' to '/Users/ludwig/Library/Application Support/CNVRanger/Example/PLINK/plink-1.07-mac-intel/plink.gvar.summary.BT', reason 'No such file or directory'
2: In file(file, "rt") :
  cannot open file '/Users/ludwig/Library/Application Support/CNVRanger/Example/PLINK/plink-1.07-mac-intel/plink.gvar.summary.BT': No such file or directory

Now I think the main problem here is just that we need to upgrade to a newer plink version:

https://www.biostars.org/p/439220/

**Comment by viniciushdasilva** [comment] 2021-04-27 23:01
Hi @lgeistlinger, I can see the error. It has to do with plink setup. If you run `setupCnvGWAS()` twice it solves the  first error, i.e:

```
Error in system2(plink.path, args = "--noweb", stdout = TRUE, stderr = FALSE) : 
  error in running command
```
However, other errors due to plink usage can occur as show in the issue #25 and unfortunately the new plink version cannot be used with the `--gfile ` argument, which is used by current `cnvGWAS()`. Thus, a proper fix is only going to happen in our upcoming upgrade that will replace plink by `lm()` to perform linear regressions.

**Comment by viniciushdasilva** [comment] 2021-04-27 23:06
Hi @SaraNara, although the problem cannot be quickly fixed, I suggested an alternative solution for the issue #25 that may help you.  Please let me know if you have any problems!

**Comment by viniciushdasilva** [comment] 2021-05-02 22:03
`cnvGWAS` function in the `master` branch was updated and linear regression is now independent of PLINK. Thus, the error should be not present in CNVRanger 1.7.3.

**Closed** 2021-05-02 22:14 UTC
